
[window]
option_as_alt = "OnlyLeft"
decorations = "Buttonless"
[font]
normal = { family ="Victor Mono", style = "Regular" }
# Default colorscaca
[colors.primary]
background ='0x201e18'
foreground ='0xc5c8c6'

# Normal colors
[colors.normal]
black =  '0x282a2e'
red =    '0xec905d'
green =  '0xb0c18b'
yellow = '0xf2bc50'
blue =   '0x587386'
magenta ='0xac7690'
cyan =   '0x5e8d87'
white =  '0xf8e9d6'

# Bright colors
[colors.bright]
black =  '0x373b41'
red =    '0xff9c64'
green =  '0xe9ffb8'
yellow = '0xffc654'
blue =   '0x6e90a8'
magenta ='0xcd8dac'
cyan =     '0x77b3ab'
white =  '0xd1c4b4'
